# Pandas Exercise II

In [13]:
import pandas as pd

First, we will load the dataset from `data/AAPL.csv` into a DataFrame.

In [14]:
df = pd.read_csv('../data/AAPL.csv')
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-06-30,125.570000,126.120003,124.860001,125.430000,115.597382,44370700
1,2015-07-01,126.900002,126.940002,125.989998,126.599998,116.675667,30238800
2,2015-07-02,126.430000,126.690002,125.769997,126.440002,116.528198,27211000
3,2015-07-06,124.940002,126.230003,124.849998,126.000000,116.122704,28060400
4,2015-07-07,125.889999,126.150002,123.769997,125.690002,115.837006,46946800

This data, in its raw format, is the same as that which can be retrieved from a number of financial websites.

Before starting the exercise, let's add some additional data columns, calculated from the raw data. Don't worry if you aren't familiar with the methods used in the following cell.

In [15]:
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Weekday'] = df['Date'].dt.day_name()
df['Change %'] = (df['Adj Close'].pct_change() * 100)

In [16]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Year,Month,Day,Weekday,Change %
0,2015-06-30,125.570000,126.120003,124.860001,125.430000,115.597382,44370700,2015,6,30,Tuesday,NaN
1,2015-07-01,126.900002,126.940002,125.989998,126.599998,116.675667,30238800,2015,7,1,Wednesday,0.932794
2,2015-07-02,126.430000,126.690002,125.769997,126.440002,116.528198,27211000,2015,7,2,Thursday,-0.126392
3,2015-07-06,124.940002,126.230003,124.849998,126.000000,116.122704,28060400,2015,7,6,Monday,-0.347979
4,2015-07-07,125.889999,126.150002,123.769997,125.690002,115.837006,46946800,2015,7,7,Tuesday,-0.246031

**Note**: Avoid modifying `df` itself in the subsequent questions.

#### Store the mean of the values in the `Adj Close` column in a variable called `mean_adj_close`

In [17]:
# Add your code here
mean_adj_close = df[['Adj Close']].mean()
mean_adj_close

Adj Close    167.049757
dtype: float64

#### Store the minimum value in the `Low` column in a variable called `min_low`

In [18]:
# Add your code here
min_low = df['Low'].min()
min_low

np.float64(89.470001)

#### Store the maximum value in the `High` column in a variable called `max_high`

In [19]:
# Add your code here
# Add your code here
max_high = df['High'].min()
max_high

np.float64(91.669998)

#### Store the difference between `min_low` and `max_high` in a variable called `price_range`

In [20]:
# Add your code here
price_range = min_low - max_high
price_range

np.float64(-2.1999970000000104)

#### Store how many rows are there in the DataFrame in a variable called `entries`

In [23]:
# Add your code here
entries = len(df)
entries

1259

#### Store in a variable called `positive_days`: how many days (i.e. number of rows) was `Change %` greater than zero

In [31]:
# Add your code here
positive_day_msk = df['Change %'] > 0
positive_days = len(df[positive_day_msk])
positive_days

671

#### Store in a variable called `days_higher`: how many days (i.e. number of rows) has `Adj Close` been greater than the value in the final row?

In [36]:
# Add your code here
days_higher_msk = df['Adj Close'] > df['Adj Close'].tail(1).iloc[0]
days_higher = len(df[days_higher_msk])
days_higher

2

## Dataset sorting and filtering

#### Create a new DataFrame called `df_2020` which is the same as `df` but contains only the rows where `Year == 2020`

In [38]:
# Add your code here
df_2020_msk = df['Year'] == 2020
df_2020 = df[df_2020_msk]
df_2020.sample(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Year,Month,Day,Weekday,Change %
1233,2020-05-22,315.769989,319.230011,315.350006,318.890015,318.890015,20450800,2020,5,22,Friday,0.643841
1153,2020-01-29,324.450012,327.850006,321.380005,324.339996,322.698517,54057300,2020,1,29,Wednesday,2.093232
1140,2020-01-09,307.239990,310.429993,306.200012,309.630005,308.062988,42527100,2020,1,9,Thursday,2.124092
1169,2020-02-21,318.619995,320.450012,310.500000,313.049988,312.204865,32388500,2020,2,21,Friday,-2.263497
1234,2020-05-26,323.500000,324.239990,316.500000,316.730011,316.730011,31380500,2020,5,26,Tuesday,-0.677351
1207,2020-04-16,287.380005,288.200012,282.350006,286.690002,285.916046,39281300,2020,4,16,Thursday,0.794574
1152,2020-01-28,312.600006,318.399994,312.190002,317.690002,316.082184,40558500,2020,1,28,Tuesday,2.828938
1141,2020-01-10,310.600006,312.670013,308.250000,310.329987,308.759399,35161200,2020,1,10,Friday,0.226061
1206,2020-04-15,282.399994,286.329987,280.630005,284.429993,283.662140,32788600,2020,4,15,Wednesday,-0.912729
1230,2020-05-19,315.029999,318.519989,313.010010,313.140015,313.140015,25432400,2020,5,19,Tuesday,-0.577844

#### Continuing using `df_2020`: Store in a variable called `mean_change_mon_2020` the calculation of the `.mean()` of `Change %` for entries where `Weekday == Monday`

In [47]:
# Add your code here
mean_change_mon_2020_msk = df_2020['Weekday'] == 'Monday'
mean_change_mon_2020 = df_2020[mean_change_mon_2020_msk]['Change %'].mean()
mean_change_mon_2020

np.float64(0.2918877852311579)

#### When you have calculated `mean_change_mon_2020`, uncomment and run the cell below to view its value:

In [ ]:
# mean_change_mon_2020

#### Calculate the sum of the `Volume` column in `df_2020` for entries where `Month == 3` and store the value in a variable called `total_volume_march_2020`

In [55]:
# Add your code here
month3_msk = df_2020['Month'] == 3
total_volume_march_2020 = df_2020['Volume'][month3_msk].sum()
total_volume_march_2020

np.int64(1570018100)

#### When you have calculated `total_volume_march_2020`, uncomment and run the cell below to view its value

In [56]:
total_volume_march_2020

np.int64(1570018100)

#### Using `df_2020`, determine when `Adj Close` was the highest, store the value in a variable called `year_high_timestamp`

- look at the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.idxmax.html) for the `.idxmax()` method and use it for this task

In [70]:
# Add your code here
year_high_timestamp = df_2020['Adj Close'].idxmax()
year_high_timestamp

np.int64(1254)

#### Create a DataFrame called `df_top_10` which contains the 10 entries from `df` with the highest positive `Change %` values.
- consider all entries in `df` rather than `df_2020`
- remember to avoid modifying `df` or any other stored DataFrames 
- `.copy()` can be used to copy a DataFrame to a new variable

In [ ]:
# Add your code here
df_change_highest = df.sort_values(by='Change %', ascending=False)
df_top_10 = df_change_highest.head(10).copy()

,Date,Open,High,Low,Close,Adj Close,Volume,Year,Month,Day,Weekday,Change %
1184,2020-03-13,264.890015,279.920013,252.949997,277.970001,277.219574,92683000,2020,3,13,Friday,11.980825
1191,2020-03-24,236.360001,247.690002,234.300003,246.880005,246.213516,71882800,2020,3,24,Tuesday,10.032544
1175,2020-03-02,282.279999,301.440002,277.720001,298.809998,298.003296,85349300,2020,3,2,Monday,9.310065
1200,2020-04-06,250.899994,263.109985,249.380005,262.470001,261.761414,50455100,2020,4,6,Monday,8.723748
1181,2020-03-10,277.140015,286.440002,269.369995,285.339996,284.569672,71322500,2020,3,10,Tuesday,7.202155
879,2018-12-26,148.300003,157.229996,146.720001,157.169998,154.059814,58582500,2018,12,26,Wednesday,7.042139
902,2019-01-30,163.250000,166.149994,160.229996,165.250000,161.979935,61109800,2019,1,30,Wednesday,6.833477
271,2016-07-27,104.269997,104.349998,102.750000,102.949997,96.822357,92344800,2016,7,27,Wednesday,6.496310
401,2017-02-01,127.029999,130.490005,127.010002,128.750000,122.367752,111985000,2017,2,1,Wednesday,6.098075
778,2018-08-01,199.130005,201.759995,197.309998,201.500000,196.137955,67935700,2018,8,1,Wednesday,5.891019

#### How many entries in `df_top_10` were *not* on a Monday? Store the value in a variable called `top_10_not_mon`

In [84]:
# Add your code here
not_monday_msk = df_top_10['Weekday'] != 'Monday'
top_10_not_mon = len(df_top_10[not_monday_msk])
top_10_not_mon

8

#### When you have calculate `top_10_not_mon`, uncomment and run the cell below to inspect it

In [85]:
top_10_not_mon

8

## Dataset manipulation

#### Copy the original `df` dataFrame and call the new dataframe `df_var`.  Give it a new column called `Variation %` equal to ((`High` - `Low`) / `Close`) * 100.
- be sure to use `Close` rather than `Adj Close` in this question
- do not modify `df` but create a copy: `df_var = df.copy()`

In [98]:
# Add your code here
df_var = df.copy()
df_var['Variation %'] = ((df_var['High'] - df_var['Low']) / df_var['Close']) * 100
df_var.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Year,Month,Day,Weekday,Change %,Variation %
0,2015-06-30,125.570000,126.120003,124.860001,125.430000,115.597382,44370700,2015,6,30,Tuesday,NaN,1.004546
1,2015-07-01,126.900002,126.940002,125.989998,126.599998,116.675667,30238800,2015,7,1,Wednesday,0.932794,0.750398
2,2015-07-02,126.430000,126.690002,125.769997,126.440002,116.528198,27211000,2015,7,2,Thursday,-0.126392,0.727622
3,2015-07-06,124.940002,126.230003,124.849998,126.000000,116.122704,28060400,2015,7,6,Monday,-0.347979,1.095242
4,2015-07-07,125.889999,126.150002,123.769997,125.690002,115.837006,46946800,2015,7,7,Tuesday,-0.246031,1.893552

#### Once you have calculated `df_var`, you can uncomment and run the cell below to inspect it

In [100]:
df_var.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Year,Month,Day,Weekday,Change %,Variation %
0,2015-06-30,125.570000,126.120003,124.860001,125.430000,115.597382,44370700,2015,6,30,Tuesday,NaN,1.004546
1,2015-07-01,126.900002,126.940002,125.989998,126.599998,116.675667,30238800,2015,7,1,Wednesday,0.932794,0.750398
2,2015-07-02,126.430000,126.690002,125.769997,126.440002,116.528198,27211000,2015,7,2,Thursday,-0.126392,0.727622
3,2015-07-06,124.940002,126.230003,124.849998,126.000000,116.122704,28060400,2015,7,6,Monday,-0.347979,1.095242
4,2015-07-07,125.889999,126.150002,123.769997,125.690002,115.837006,46946800,2015,7,7,Tuesday,-0.246031,1.893552