# Pandas Exercise II

In [1]:
import pandas as pd

First, we will load the dataset from `data/AAPL.csv` into a DataFrame.

In [2]:
df = pd.read_csv('../data/AAPL.csv')
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-06-30,125.570000,126.120003,124.860001,125.430000,115.597382,44370700
1,2015-07-01,126.900002,126.940002,125.989998,126.599998,116.675667,30238800
2,2015-07-02,126.430000,126.690002,125.769997,126.440002,116.528198,27211000
3,2015-07-06,124.940002,126.230003,124.849998,126.000000,116.122704,28060400
4,2015-07-07,125.889999,126.150002,123.769997,125.690002,115.837006,46946800

This data, in its raw format, is the same as that which can be retrieved from a number of financial websites.

Before starting the exercise, let's add some additional data columns, calculated from the raw data. Don't worry if you aren't familiar with the methods used in the following cell.

In [3]:
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Weekday'] = df['Date'].dt.day_name()
df['Change %'] = (df['Adj Close'].pct_change() * 100)

In [4]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Year,Month,Day,Weekday,Change %
0,2015-06-30,125.570000,126.120003,124.860001,125.430000,115.597382,44370700,2015,6,30,Tuesday,NaN
1,2015-07-01,126.900002,126.940002,125.989998,126.599998,116.675667,30238800,2015,7,1,Wednesday,0.932794
2,2015-07-02,126.430000,126.690002,125.769997,126.440002,116.528198,27211000,2015,7,2,Thursday,-0.126392
3,2015-07-06,124.940002,126.230003,124.849998,126.000000,116.122704,28060400,2015,7,6,Monday,-0.347979
4,2015-07-07,125.889999,126.150002,123.769997,125.690002,115.837006,46946800,2015,7,7,Tuesday,-0.246031

**Note**: Avoid modifying `df` itself in the subsequent questions.

#### Store the mean of the values in the `Adj Close` column in a variable called `mean_adj_close`

In [5]:
# Add your code here
mean_adj_close = df['Adj Close'].mean()
mean_adj_close

np.float64(167.04975667513898)

#### Store the minimum value in the `Low` column in a variable called `min_low`

In [6]:
# Add your code here
min_low = df['Low'].min()
min_low

np.float64(89.470001)

#### Store the maximum value in the `High` column in a variable called `max_high`

In [7]:
# Add your code here
# Add your code here
max_high = df['High'].max()
max_high

np.float64(372.380005)

#### Store the difference between `min_low` and `max_high` in a variable called `price_range`

In [8]:
# Add your code here
price_range = max_high - min_low
price_range

np.float64(282.91000399999996)

#### Store how many rows are there in the DataFrame in a variable called `entries`

In [27]:
# Add your code here
entries = len(df)
entries
len(df.columns)
df.shape[1]

12

#### Store in a variable called `positive_days`: how many days (i.e. number of rows) was `Change %` greater than zero

In [10]:
# Add your code here
positive_day_msk = df['Change %'] > 0
positive_days = len(df[positive_day_msk])
positive_days

671

#### Store in a variable called `days_higher`: how many days (i.e. number of rows) has `Adj Close` been greater than the value in the final row?

In [28]:
# Add your code here
days_higher_msk = df['Adj Close'] > df['Adj Close'].tail(1).iloc[0]
days_higher = len(df[days_higher_msk])
days_higher

2

In [29]:
final_day = df.loc[len(df) - 1, 'Adj Close']

days_higher = len(df[df['Adj Close'] > final_day])
days_higher

2

## Dataset sorting and filtering

#### Create a new DataFrame called `df_2020` which is the same as `df` but contains only the rows where `Year == 2020`

In [12]:
# Add your code here
df_2020_msk = df['Year'] == 2020
df_2020 = df[df_2020_msk]
df_2020.sample(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Year,Month,Day,Weekday,Change %
1258,2020-06-29,353.250000,362.170013,351.279999,361.779999,361.779999,32579000,2020,6,29,Monday,2.304667
1159,2020-02-06,322.570007,325.220001,320.260010,325.209991,323.564117,26356400,2020,2,6,Thursday,1.169689
1246,2020-06-11,349.309998,351.059998,335.480011,335.899994,335.899994,50415600,2020,6,11,Thursday,-4.801044
1240,2020-06-03,324.660004,326.200012,322.299988,325.119995,325.119995,26122800,2020,6,3,Wednesday,0.550504
1227,2020-05-14,304.510010,309.790009,301.529999,309.540009,309.540009,39732300,2020,5,14,Thursday,0.614339
1214,2020-04-27,281.799988,284.540009,279.950012,283.170013,282.405548,29271900,2020,4,27,Monday,0.070680
1212,2020-04-23,275.869995,281.750000,274.869995,275.029999,274.287506,31203600,2020,4,23,Thursday,-0.387540
1255,2020-06-24,365.000000,368.790009,358.519989,360.059998,360.059998,48155800,2020,6,24,Wednesday,-1.765204
1153,2020-01-29,324.450012,327.850006,321.380005,324.339996,322.698517,54057300,2020,1,29,Wednesday,2.093232
1197,2020-04-01,246.500000,248.720001,239.130005,240.910004,240.259628,44054600,2020,4,1,Wednesday,-5.261707

In [32]:
# Add your code below
# df_2020 = ...
df_2020_new = df[df['Year'] == 2020]
df_2020_new.set_index('Date', inplace=True)
df_2020_new.head()

,Open,High,Low,Close,Adj Close,Volume,Year,Month,Day,Weekday,Change %
Date,,,,,,,,,,,
2020-01-02,296.239990,300.600006,295.190002,300.350006,298.829956,33870100,2020,1,2,Thursday,2.281644
2020-01-03,297.149994,300.579987,296.500000,297.429993,295.924713,36580700,2020,1,3,Friday,-0.972206
2020-01-06,293.790009,299.959991,292.750000,299.799988,298.282715,29596800,2020,1,6,Monday,0.796825
2020-01-07,299.839996,300.899994,297.480011,298.390015,296.879883,27218000,2020,1,7,Tuesday,-0.470303
2020-01-08,297.160004,304.440002,297.160004,303.190002,301.655548,33019800,2020,1,8,Wednesday,1.608619

#### Continuing using `df_2020`: Store in a variable called `mean_change_mon_2020` the calculation of the `.mean()` of `Change %` for entries where `Weekday == Monday`

In [13]:
# Add your code here
mean_change_mon_2020_msk = df_2020['Weekday'] == 'Monday'
mean_change_mon_2020 = df_2020[mean_change_mon_2020_msk]['Change %'].mean()
mean_change_mon_2020

np.float64(0.2918877852311579)

#### When you have calculated `mean_change_mon_2020`, uncomment and run the cell below to view its value:

In [14]:
# mean_change_mon_2020

#### Calculate the sum of the `Volume` column in `df_2020` for entries where `Month == 3` and store the value in a variable called `total_volume_march_2020`

In [15]:
# Add your code here
month3_msk = df_2020['Month'] == 3
total_volume_march_2020 = df_2020['Volume'][month3_msk].sum()
total_volume_march_2020

np.int64(1570018100)

In [35]:
# Add your code below
total_volume_march_2020_new = df_2020[df_2020['Month'] == 3]['Volume'].sum()
total_volume_march_2020_new

np.int64(1570018100)

#### When you have calculated `total_volume_march_2020`, uncomment and run the cell below to view its value

In [16]:
total_volume_march_2020

np.int64(1570018100)

#### Using `df_2020`, determine when `Adj Close` was the highest, store the value in a variable called `year_high_timestamp`

- look at the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.idxmax.html) for the `.idxmax()` method and use it for this task

In [17]:
# Add your code here
year_high_timestamp = df_2020['Adj Close'].idxmax()
year_high_timestamp

np.int64(1254)

#### Create a DataFrame called `df_top_10` which contains the 10 entries from `df` with the highest positive `Change %` values.
- consider all entries in `df` rather than `df_2020`
- remember to avoid modifying `df` or any other stored DataFrames 
- `.copy()` can be used to copy a DataFrame to a new variable

In [18]:
# Add your code here
df_change_highest = df.sort_values(by='Change %', ascending=False)
df_top_10 = df_change_highest.head(10).copy()

#### How many entries in `df_top_10` were *not* on a Monday? Store the value in a variable called `top_10_not_mon`

In [19]:
# Add your code here
not_monday_msk = df_top_10['Weekday'] != 'Monday'
top_10_not_mon = len(df_top_10[not_monday_msk])
top_10_not_mon

8

#### When you have calculate `top_10_not_mon`, uncomment and run the cell below to inspect it

In [20]:
top_10_not_mon

8

## Dataset manipulation

#### Copy the original `df` dataFrame and call the new dataframe `df_var`.  Give it a new column called `Variation %` equal to ((`High` - `Low`) / `Close`) * 100.
- be sure to use `Close` rather than `Adj Close` in this question
- do not modify `df` but create a copy: `df_var = df.copy()`

In [21]:
# Add your code here
df_var = df.copy()
df_var['Variation %'] = ((df_var['High'] - df_var['Low']) / df_var['Close']) * 100
df_var.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Year,Month,Day,Weekday,Change %,Variation %
0,2015-06-30,125.570000,126.120003,124.860001,125.430000,115.597382,44370700,2015,6,30,Tuesday,NaN,1.004546
1,2015-07-01,126.900002,126.940002,125.989998,126.599998,116.675667,30238800,2015,7,1,Wednesday,0.932794,0.750398
2,2015-07-02,126.430000,126.690002,125.769997,126.440002,116.528198,27211000,2015,7,2,Thursday,-0.126392,0.727622
3,2015-07-06,124.940002,126.230003,124.849998,126.000000,116.122704,28060400,2015,7,6,Monday,-0.347979,1.095242
4,2015-07-07,125.889999,126.150002,123.769997,125.690002,115.837006,46946800,2015,7,7,Tuesday,-0.246031,1.893552

#### Once you have calculated `df_var`, you can uncomment and run the cell below to inspect it

In [22]:
df_var.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Year,Month,Day,Weekday,Change %,Variation %
0,2015-06-30,125.570000,126.120003,124.860001,125.430000,115.597382,44370700,2015,6,30,Tuesday,NaN,1.004546
1,2015-07-01,126.900002,126.940002,125.989998,126.599998,116.675667,30238800,2015,7,1,Wednesday,0.932794,0.750398
2,2015-07-02,126.430000,126.690002,125.769997,126.440002,116.528198,27211000,2015,7,2,Thursday,-0.126392,0.727622
3,2015-07-06,124.940002,126.230003,124.849998,126.000000,116.122704,28060400,2015,7,6,Monday,-0.347979,1.095242
4,2015-07-07,125.889999,126.150002,123.769997,125.690002,115.837006,46946800,2015,7,7,Tuesday,-0.246031,1.893552